### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zodIIac-git** [iraizo/duskhaven-loader#10] opened 2023-03-25 22:33 UTC
Launched as administrator, config and .exe is placed in the game client folder, the WoW path is correctly set. Did hit update, then the program hangs for a couple minutes then crashes. Both patch files are currently up to date, was just curious how does the launcher work.
[crash.log](https://github.com/iraizo/duskhaven-loader/files/11070348/crash.log)

**Comment by emilmajstro** [comment] 2023-03-25 22:39
also duplicate of #8

**Closed** 2023-03-25 22:39 UTC
