### ISSUE TITLE
Crash log as requested.  Hope this helps.

### ISSUE THREAD

**Issue by MightBeChris** [iraizo/duskhaven-loader#33] opened 2023-03-26 19:41 UTC
[crash.log](https://github.com/iraizo/duskhaven-loader/files/11072860/crash.log)

**Comment by iraizo** [comment] 2023-03-26 19:56
Duplicate of https://github.com/iraizo/duskhaven-loader/issues/11 im investigating this

**Closed by iraizo** 2023-03-26 19:56 UTC
