### ISSUE TITLE
Launcher crashes when checking patch-5 for the updating

### ISSUE THREAD

**Issue by BubbleButt10120** [iraizo/duskhaven-loader#12] opened 2023-03-25 22:34 UTC
Whenever I try updating a game the launcher just crashes while checking the patch-5
[crash.log](https://github.com/iraizo/duskhaven-loader/files/11070349/crash.log)

**Comment by iraizo** [comment] 2023-03-25 22:37
Duplicate of https://github.com/iraizo/duskhaven-loader/issues/8

**Closed by iraizo** 2023-03-25 22:37 UTC
