### ISSUE TITLE
Crash while downloading patch Z

### ISSUE THREAD

**Issue by mickyds33** [iraizo/duskhaven-loader#13] opened 2023-03-25 22:35 UTC
panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: hyper::Error(Body, Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." }) }', src/updater.rs:112:63

Patched as administrator just in case and I think I got the DDoS message mentioned in another post

**Comment by iraizo** [comment] 2023-03-25 22:37
Duplicate of https://github.com/iraizo/duskhaven-loader/issues/8

**Closed by iraizo** 2023-03-25 22:37 UTC
