### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by darkjesterr** [iraizo/duskhaven-loader#9] opened 2023-03-25 22:27 UTC
crash after pressing update

panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(88.198.38.70)), port: Some(8443), path: "/patch-5.mpq", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." })) }', src/updater.rs:77:63

**Comment by iraizo** [comment] 2023-03-25 22:30
Duplicate of #8

**Closed by iraizo** 2023-03-25 22:30 UTC
